### ISSUE TITLE
Beadandó

### ISSUE THREAD

**Issue by GergelyPapa** [Teaching-projects/januari-beadando-GergelyPapa#1]
Szép estét Tanár úr!

Itt lenne az első változata a programomnak.

**Comment by hegyhati** [comment]
No, alapvetoen rendben lesz ez, csak tegyunk rendbe par dolgot. A fuggvenyesdi lenyeget kicsit felreertetted. Annak ugy semmi ertelme, hogy van egy fuggvenyed, es abba teszel mindet. Ennyi erovel a "foprogramba" is irhattad volna az egeszet.

Ami kulonosen csunya, az az, hogy az elif-ekben rekurzivan meghivod ezt a fuggvenyt, majd utana van egy break. Probald vegignyomogatni pythontutorban mi tortenik ilyenkor, ez egy nagy mess.

Szoval a javaslatom: csinalj olyan fuggvenyeket, amiknek tenyleg van is ertelme, pl "negyzet_kerulet" es tarsai. majd ezek legyenek megfeleloen hivogatva a forpogramban.

Rendben lesz ez, csak ezeket a while True, break, rekurziv hivasos dolgokat kellene kiganezni belole.

**Comment by hegyhati** [comment]
```python
def szamitas():
    mit = input("sldkfjslkdfjsldfjkslkdfj")
    if mit=="terulet":
        teruletszamitas()
    elif mit == "kerulet":
        keruletszamitast()


szeretne = True

while szeretne:
    szamitas()
    szeretnel = input("sjdfklajsflakjsdf")
    szeretne = (szeretnel == "igen")
```

**Comment by GergelyPapa** [comment]
Szép estét Tanár úr!

Javítottam a feladatot! :D

**Comment by hegyhati** [comment]
nem teljesen erre gondoltam, de ok, elfogadom, 5.
